### ISSUE TITLE
Is there a way to replay on client side?

### ISSUE THREAD

**Issue by fhg-isi** [puppeteer/replay#730]
Is there a way to replay recorded flows on client side, for example in a google chrome snippet (including for loops etc.)?
Also see
https://stackoverflow.com/questions/77745367/how-to-use-recorded-puppeteer-like-automation-commands-client-side-e-g-as-go

**Comment by Chirsdon** [comment]
- [
[README.md](https://github.com/puppeteer/replay/files/14047459/README.md)
](url)

**Comment by OrKoN** [comment]
There is currently no way to do this from the snippets because replay requires a CDP connection and snippets do not provide access to it. You can run the replay from an extension though https://github.com/puppeteer/replay?tab=readme-ov-file#create-a-chrome-extension-for-recorder-available-from-chrome-104-onwards
